services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${INTELLIGUARD_DB_NAME}
      POSTGRES_USER: ${INTELLIGUARD_DB_USERNAME}
      POSTGRES_PASSWORD: ${INTELLIGUARD_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${INTELLIGUARD_DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"   # UI
      - "4317:4317"     # OTLP gRPC
      - "4318:4318"     # OTLP HTTP

  backend-core:
    build: ../backend-core
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      jaeger:
        condition: service_started
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/${INTELLIGUARD_DB_NAME}
      DB_USERNAME: ${INTELLIGUARD_DB_USERNAME}
      DB_PASSWORD: ${INTELLIGUARD_DB_PASSWORD}

  ml-service:
    build: ../ml-service
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ../frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend-core

  simulator:
    build: ../simulator
    depends_on:
      - backend-core
      - jaeger
    environment:
      BACKEND_URL: http://backend-core:8080
      OTLP_ENDPOINT: jaeger:4317
      TICK_SECONDS: "5"
      SIMULATOR_ADMIN_PASSWORD: ${INTELLIGUARD_SIMULATOR_ADMIN_PASSWORD}

volumes:
  pgdata:
