"""Train the scoring service's default detector from simulator-generated NORMAL data.

    python -m app.train            # runs at Docker build time (see Dockerfile)

Settings (detector, hyperparameters, training seeds) come from app/model_config.json, which
evaluation/run_experiments.py writes after choosing them on VALIDATION data. No database access:
the training data is generated by the simulator's own offline generator.
"""
from __future__ import annotations

import json
import os
import tempfile

import joblib

from .data import generate, load_run, normal_training_data
from .detectors import build

CONFIG_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "model_config.json")
DEFAULT_MODEL_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "models")
MODEL_FILE = "default.joblib"


def model_dir():
    return os.environ.get("MODEL_DIR", DEFAULT_MODEL_DIR)


def train_and_save(out_dir=None, seeds=None, days=None, minutes=None):
    """Fit the configured default detector on normal-mode data and save it with joblib.
    seeds/days/minutes override the config (tests use a small run)."""
    with open(CONFIG_PATH) as f:
        cfg = json.load(f)
    name = cfg["default_detector"]
    seeds = seeds or cfg["train"]["seeds"]
    days = cfg["train"]["days"] if days is None and minutes is None else (days or 0)

    with tempfile.TemporaryDirectory() as tmp:
        runs = [load_run(generate(os.path.join(tmp, f"normal-s{s}"), s, "normal", days=days, minutes=minutes or 0), s, "normal")
                for s in seeds]
    detector = build(name, cfg["detectors"][name]).fit(normal_training_data(runs))

    out_dir = out_dir or model_dir()
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, MODEL_FILE)
    joblib.dump({"name": name, "detector": detector, "config": cfg,
                 "trained_on": {"seeds": seeds, "days": days, "minutes": minutes, "mode": "normal"}}, path)
    return path


if __name__ == "__main__":
    print("saved", train_and_save())
